services:
  gpu-app:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - MODEL_ID=WhereIsAI/UAE-Large-V1
      - VLLM_MODEL_ID=mrfakename/mistral-small-3.1-24b-instruct-2503-hf
      - VLLM_GPU_UTILIZATION=0.8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
